package com.kehnestudio.procrastinator_proccy

object Constants {
    const val ACTION_START_SERVICE = "ACTION_START_TIMER"
    const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"
    const val ACTION_SHOW_GOALS_FRAGMENT = "ACTION_SHOW_GOALS_FRAGMENT"
    const val ACTION_SHOW_LOGIN_FRAGMENT = "ACTION_SHOW_LOGIN_FRAGMENT"
    const val ACTION_SHOW_HOME_FRAGMENT = "ACTION_SHOW_HOME_FRAGMENT"
    const val EXTRA_TIMER_LENGTH = "EXTRA_TIMER_LENGTH"

    const val NOTIFICATION_CHANNEL_ID = "timer_channel"
    const val NOTIFICATION_CHANNEL_NAME = "Timer"
    const val NOTIFICATION_ID = 1

    const val PERIODIC_WORK_UPLOAD_DATA = "UPLOAD_DATA_TO_FIRESTORE_WORK"


}